import { setupI18n } from '@lingui/core'
import type { I18n, Messages } from '@lingui/core'
import { 
  locales, 
  defaultLocale, 
  type Locale, 
  type MessageCatalog,
  LocaleError,
  TranslationError 
} from './types'

// Re-export types for convenience
export type { Locale, MessageCatalog, LocaleError, TranslationError }
export { locales, defaultLocale }

// Initialize i18n instance with proper typing and placeholder messages to suppress warnings
export const i18n: I18n = setupI18n({
  locale: defaultLocale,
  messages: {
    // Initialize with empty messages for all supported locales to suppress warnings
    en: {},
    ar: {}
  },
  missing: (locale: string, id: string): string => {
    // Only log missing translations in development for actual translation keys
    // Ignore hash-based message IDs (generated by Lingui)
    if (process.env.NODE_ENV === 'development' && id && !id.match(/^[a-zA-Z0-9+/]+$/)) {
      console.warn(`Missing translation for "${id}" in locale "${locale}"`)
    }
    return id // Return the message ID as fallback
  },
  // Add locale data to prevent warnings
  localeData: {
    en: { plurals: () => 'other' },
    ar: { plurals: () => 'other' }
  }
})

/**
 * Dynamically loads and activates a locale with proper error handling
 * @param locale - The locale to activate
 * @throws {LocaleError} When locale loading fails
 */
export async function activateLocale(locale: string): Promise<void> {
  try {
    // Validate locale before attempting to load
    if (!isValidLocale(locale)) {
      throw new LocaleError(`Invalid locale: ${locale}`, locale)
    }

    // Dynamic import of locale messages with proper typing
    const { messages }: { messages: MessageCatalog } = await import(`../locales/${locale}/messages.js`)
    
    // Validate messages structure
    if (!messages || typeof messages !== 'object') {
      throw new LocaleError(`Invalid message catalog for locale: ${locale}`, locale)
    }
    
    // Load messages into i18n instance
    i18n.load(locale, messages)
    
    // Activate the locale
    i18n.activate(locale)
    
    // Development mode logging
    if (process.env.NODE_ENV === 'development') {
      console.log(`✅ Activated locale: ${locale} (${Object.keys(messages).length} messages)`)
    }
  } catch (error) {
    const errorMessage = `Failed to load locale "${locale}"`
    console.error(errorMessage, error)
    
    // Create typed error
    const localeError = error instanceof LocaleError 
      ? error 
      : new LocaleError(errorMessage, locale)
    
    // Fallback to default locale if not already trying default
    if (locale !== defaultLocale) {
      console.warn(`Falling back to default locale: ${defaultLocale}`)
      try {
        await activateLocale(defaultLocale)
      } catch (fallbackError) {
        throw new LocaleError(
          `Failed to load both requested locale "${locale}" and default locale "${defaultLocale}"`,
          locale
        )
      }
    } else {
      // If even default locale fails, throw error
      throw localeError
    }
  }
}

/**
 * Type-safe validation for supported locales
 * @param locale - The locale string to validate
 * @returns Type predicate confirming if locale is supported
 */
export function isValidLocale(locale: string): locale is Locale {
  return locales.includes(locale as Locale)
}

/**
 * Gets the current active locale with type safety
 * @returns The currently active locale
 */
export function getCurrentLocale(): Locale {
  const currentLocale = i18n.locale
  
  // Ensure the current locale is valid, fallback to default if not
  if (isValidLocale(currentLocale)) {
    return currentLocale
  }
  
  console.warn(`Invalid current locale "${currentLocale}", falling back to default`)
  return defaultLocale
}

/**
 * Checks if the current locale uses RTL text direction
 * @returns True if current locale is RTL
 */
export function isRTL(): boolean {
  return getCurrentLocale() === 'ar'
}

/**
 * Gets the text direction for the current locale
 * @returns 'rtl' for Arabic, 'ltr' for others
 */
export function getTextDirection(): 'ltr' | 'rtl' {
  return isRTL() ? 'rtl' : 'ltr'
}

/**
 * Type-safe translation function with error handling
 * @param messageId - The message ID to translate
 * @param values - Optional values for interpolation
 * @returns Translated string
 */
export function translate(messageId: string, values?: Record<string, any>): string {
  try {
    return i18n._(messageId, values)
  } catch (error) {
    console.error(`Translation error for message "${messageId}":`, error)
    
    if (process.env.NODE_ENV === 'development') {
      throw new TranslationError(
        `Failed to translate message: ${messageId}`,
        messageId,
        getCurrentLocale()
      )
    }
    
    return messageId // Fallback to message ID
  }
}

// Re-export server utilities for convenience
export {
  getI18nInstance,
  setupServerI18n,
  detectServerLocale,
  initializeServerI18n,
  getServerLocale,
  preloadMessages,
  createServerI18nWithMessages
} from './server'

// Re-export client provider and hooks
export {
  LinguiClientProvider,
  useLocale,
  useCurrentLocale,
  triggerLocaleChange
} from './LinguiClientProvider'

// Re-export safe Lingui hook
export { useSafeLingui } from './useSafeLingui'

// Re-export type-safe utilities
export {
  safeTranslate,
  hasMessage,
  getMessageIds,
  validateMessageValues,
  createMessage,
  createPluralMessage,
  createSelectMessage,
  extractMessageIds,
  findMissingTranslations,
  validateMessageCatalog
} from './message-utils'

// Development tools are available separately to avoid client-side issues
// Import from './dev-tools' directly when needed on server-side

// Re-export all types for convenience
export type * from './types'